#!/bin/bash

# $1 = input .uC file
# $2 = output file for the assembly code
# $3 (optional) = number of registers

if [ $# -eq 3 ]; then
    # If three arguments are given, include the register count
    java -cp "$CLASSPATH:classes" compiler.Compiler "$1" "$3" > "$2"
else
    # If only two arguments, run compiler without register count argument
    java -cp "$CLASSPATH:classes" compiler.Compiler "$1" > "$2"
fi
